server:
  port: 8083

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update # update or validate

logging.level:
  org.hibernate.SQL: debug

logging-module:
  version: 0.0.3

