server:
  port: 8083

spring:
#  main:
#    allow-bean-definition-overriding: true
  profiles:
    default: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: leekunsin
    password: 1234