server:
  port: 8081

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none # validate or none

logging.level:
  org.hibernate.SQL: off

logging-module:
  version: 0.0.1

