server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    group:
      "local" : "local"
      "dev" : "dev"
      "prod" : "prod"
    default: prod

logging-module:
  version: 0.0.2


## application.yml
#
#logging-module:
#  version: 0.0.2
#
#server:
#  port: 8081
#
#spring:
#  config:
#    activate:
#      on-profile: prod
#  main:
#    allow-bean-definition-overriding: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: leekunsin
#    password: 1234
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create # 'none' or 'create'
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        jdbc:
#          time_zone: Asia/Seoul
