server:
  port: 8080

spring:
#  main:
#    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: local

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create # 'none' or 'create'
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul

logging-module:
  version: 0.0.0

