#version: 0.0
#os: linux
#files:
#  - source: /
#    destination: /home/ubuntu/sodev-project
#    overwrite: yes
#
#permissions:
#  - object: /
#    pattern: "**"
#    owner: ubuntu
#    group: ubuntu
#
#hooks:
#  ApplicationStart:
#    - location: /sodev-api/scripts/gh_deploy.sh
#      timeout: 60
#      runas: ubuntu




version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sodev-project
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

### 새로 추가한 부분 ###
hooks:
  ApplicationStart:
    - location: /sodev-api/scripts/run_new_was.sh
      timeout: 60
      runas: ubuntu
    - location: /sodev-api/scripts/health_check.sh
      timeout: 60
      runas: ubuntu
    - location: /sodev-api/scripts/switch.sh
      timeout: 60
      runas: ubuntu